# Generated by Django 5.2.6 on 2025-09-13 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('department', models.CharField(choices=[('General Medicine', 'General Medicine'), ('Cardiology', 'Cardiology'), ('Neurology', 'Neurology'), ('Orthopedics', 'Orthopedics')], max_length=50)),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.CharField(choices=[('9:00 am to 10:30 am', '9:00 am to 10:30 am'), ('11:00 am to 1:00 pm', '11:00 am to 1:00 pm'), ('2:30 pm to 3:30 pm', '2:30 pm to 3:30 pm'), ('4:00 pm to 5:00 pm', '4:00 pm to 5:00 pm')], max_length=50)),
                ('additional_requirements', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Appointments',
                'ordering': ['-preferred_date', 'full_name'],
            },
        ),
    ]
